const COUNTRIES = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Birmanie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo (République du)",
  "Congo (RDC)",
  "Corée du Nord",
  "Corée du Sud",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "Eswatini",
  "États-Unis",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Îles Marshall",
  "Îles Salomon",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine du Nord",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "République centrafricaine",
  "République dominicaine",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Christophe-et-Niévès",
  "Sainte-Lucie",
  "Saint-Marin",
  "Saint-Vincent-et-les-Grenadines",
  "Salvador",
  "Samoa",
  "Sao Tomé-et-Principe",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Tchéquie",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Yémen",
  "Zambie",
  "Zimbabwe"
];

const COUNTRY_ALIASES = {
  "Allemagne": [
    "germany",
    "allemand",
    "allemande"
  ],
  "Arabie saoudite": [
    "saudi arabia",
    "saoudien",
    "saoudienne"
  ],
  "Australie": [
    "australia",
    "australien",
    "australienne"
  ],
  "Brésil": [
    "brazil",
    "brésilien",
    "brésilienne"
  ],
  "Canada": [
    "canada",
    "canadien",
    "canadienne"
  ],
  "Chine": [
    "china",
    "chinois",
    "chinoise",
    "pékin",
    "beijing"
  ],
  "Corée du Nord": [
    "north korea",
    "nord-coréen",
    "nord-coréenne",
    "pyongyang"
  ],
  "Corée du Sud": [
    "south korea",
    "sud-coréen",
    "sud-coréenne",
    "séoul",
    "seoul"
  ],
  "Côte d’Ivoire": [
    "côte d'ivoire",
    "cote d'ivoire",
    "ivory coast",
    "ivoirien",
    "ivoirienne"
  ],
  "Égypte": [
    "egypt",
    "égyptien",
    "égyptienne"
  ],
  "Émirats arabes unis": [
    "united arab emirates",
    "uae",
    "émirati",
    "émiratie"
  ],
  "Espagne": [
    "spain",
    "espagnol",
    "espagnole"
  ],
  "États-Unis": [
    "united states",
    "usa",
    "u.s.",
    "u.s.a.",
    "américain",
    "américaine",
    "washington"
  ],
  "France": [
    "france",
    "français",
    "française",
    "paris"
  ],
  "Inde": [
    "india",
    "indien",
    "indienne",
    "new delhi"
  ],
  "Indonésie": [
    "indonesia",
    "indonésien",
    "indonésienne"
  ],
  "Iran": [
    "iran",
    "iranien",
    "iranienne",
    "téhéran",
    "tehran"
  ],
  "Irak": [
    "iraq",
    "irakien",
    "irakienne"
  ],
  "Israël": [
    "israel",
    "israélien",
    "israélienne"
  ],
  "Italie": [
    "italy",
    "italien",
    "italienne",
    "rome"
  ],
  "Japon": [
    "japan",
    "japonais",
    "japonaise",
    "tokyo"
  ],
  "Mexique": [
    "mexico",
    "mexicain",
    "mexicaine"
  ],
  "Nouvelle-Zélande": [
    "new zealand",
    "néo-zélandais",
    "néo-zélandaise"
  ],
  "Pakistan": [
    "pakistan",
    "pakistanais",
    "pakistanaise"
  ],
  "Palestine": [
    "palestine",
    "palestinien",
    "palestinienne",
    "gaza",
    "cisjordanie"
  ],
  "Pays-Bas": [
    "netherlands",
    "néerlandais",
    "néerlandaise"
  ],
  "Pologne": [
    "poland",
    "polonais",
    "polonaise"
  ],
  "Royaume-Uni": [
    "united kingdom",
    "uk",
    "britannique",
    "british",
    "londres",
    "london"
  ],
  "Russie": [
    "russia",
    "russe",
    "moscou",
    "moscow",
    "kremlin"
  ],
  "Soudan": [
    "sudan",
    "soudanais",
    "soudanaise"
  ],
  "Soudan du Sud": [
    "south sudan",
    "sud-soudanais",
    "sud-soudanaise"
  ],
  "Suisse": [
    "switzerland",
    "suisse"
  ],
  "Taïwan": [
    "taiwan",
    "taïwanais",
    "taïwanaise"
  ],
  "Turquie": [
    "turkey",
    "türkiye",
    "turc",
    "turque",
    "ankara"
  ],
  "Ukraine": [
    "ukraine",
    "ukrainien",
    "ukrainienne",
    "kyiv",
    "kiev"
  ],
  "Venezuela": [
    "venezuela",
    "vénézuélien",
    "vénézuélienne"
  ],
  "Yémen": [
    "yemen",
    "yéménite",
    "houthis",
    "houthi"
  ]
};
